version: '3'

services:
  game_service:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "2000:2000"
    env_file:
      - ./backend/.env
    networks:
      - backend

  



networks:
  backend:
  