version: '3'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
     
    ports:
      - "2000:2000"
    env_file:
      - ./backend/.env
      
    command: >
      sh -c "npm install && npm start"
    
    networks:
    
      - backend

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
    
      - "5173:5173"
    networks:
      - frontend
  



networks:
  backend:
  frontend:
  